/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package artefato4;

import java.awt.Color;
import java.awt.Rectangle;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Computador01
 */
public class jfrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form jfrmPrincipal
     */
   
   
    public jfrmLogin() {
        
         
         initComponents();
         LayoutPadrao lp = new LayoutPadrao();
        lp.ativarLayoutPadrao();
        this.setSize(750,500);//tamanho do frame
        setLocationRelativeTo(null);
        
        
       
        //setExtendedState(jfrmPrincipal.MAXIMIZED_BOTH);// Colocar Frame Tela Inteira
        // panel.getParent().setLayout(null);  
       // panel.setBounds(new Rectangle(posicaoX,posicaoY,largura,altura));  
        //panel.repaint();  CENTRALIZAR COMPONENTES
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtCPF = new javax.swing.JTextField();
        jbtnEntrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextSenha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bem vindo ao Sistema de Gerenciamento Clube de Campo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 300, 160, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("digite o CPF:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 100, 87, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 170, 48, 17);

        jtxtCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jtxtCPF);
        jtxtCPF.setBounds(280, 120, 160, 28);

        jbtnEntrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnEntrar.setText("Entrar");
        jbtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEntrar);
        jbtnEntrar.setBounds(280, 250, 160, 30);

        jButton1.setText("Cadastrar Usuário");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 360, 130, 23);
        getContentPane().add(jTextSenha);
        jTextSenha.setBounds(280, 190, 160, 30);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEntrarActionPerformed
       
        if (jtxtCPF.getText().isEmpty() || jTextSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preenchas os campos Usuários"
                    + "e Senha");
            jtxtCPF.requestFocus();
//        }  else if(jtxtCPF.getText().equals("teste")&&(jpsfSenha.getText()
//                .equals("teste"))){
//            new OpSistema().setVisible(true);
//            setVisible(false);
//        } else{
//            JOptionPane.showMessageDialog(null,"Usuário ou Senha Incorreto");
//        }                
        } else {
            PreparedStatement ps = null;
            try {
                //pega conexão
                Conexao.conectar();

                //criar uma variavel para selecionar os dados da tabela(sqlSelect)
                String sqlSelect = "select * from FUNCIONARIO where FUN_CPF ='"
                        + jtxtCPF.getText() + "'and FUN_CPF='" + jTextSenha.getText() + "'";
                //executa uma select
                ps = Conexao.con.prepareStatement(sqlSelect);
                //rs é variavel que armazenou todo o resultado (resultSet)
                ResultSet rs = ps.executeQuery(sqlSelect);
                               
                while (rs.next()) {
                     // tp = rs.getString("tipo");
//                    if(){
//                        new OpSistema().jpnlOPAdministrador.setVisible(true);
//                    }
                    JOptionPane.showMessageDialog(null, "seja bem vindo");
                     new jfrmListaSocios().setVisible(true);
                     setVisible(false);
                    //setVisible(false);
                    verificador = true;

                }
                if (verificador == false) {
                    JOptionPane.showMessageDialog(null, "Login ou senha incorretos."
                            + "\ntente novamente.",
                            "Mensagem do programa", JOptionPane.ERROR_MESSAGE);
                    jtxtCPF.setText(null);
                    jTextSenha.setText(null);
                    jtxtCPF.requestFocus();

                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao se conectar ao "
                        + "banco de dados", "Erro", JOptionPane.ERROR_MESSAGE);
                System.exit(0);

            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao conectar ao Driver"
                        + "MySQL", "Erro", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            finally{
                //fexando a conecxão
                try{
                    Conexao.con.close();
                    ps.close();
                }catch (Exception e){
                    e.printStackTrace();
                }
            }
            
        }
     

    }//GEN-LAST:event_jbtnEntrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new CadastroFuncionario().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        LayoutPadrao lp = new LayoutPadrao();
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                LayoutPadrao lp = new LayoutPadrao();
                new jfrmLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextSenha;
    private javax.swing.JButton jbtnEntrar;
    private javax.swing.JTextField jtxtCPF;
    // End of variables declaration//GEN-END:variables
boolean verificador = false;
public static String tp;

//        else if(jtxtCPF.getText().equals("teste")&&(jpsfSenha.getText()
//                .equals("teste"))){
//            new OpSistema().setVisible(true);
//            setVisible(false);
//        } else{
//            JOptionPane.showMessageDialog(null,"Usuário ou Senha Incorreto");
//        }
}
